### PR TITLE
php 8.1 github action

### PR DESCRIPTION
**Pull request by dmitryuk**
Build php 8.1 with github actions

### CODE REVIEW

**Comment by dmitryuk** [comment]
@huanghantao Merged with master, please approve running workflow

**Comment by dmitryuk** [comment]
Done

**Comment by dmitryuk** [comment]
php 8.1 still doesn't compile
https://github.com/swoole/yasd/runs/5285563445?check_suite_focus=true

**Comment by huanghantao** [comment]
> php 8.1 still doesn't compile https://github.com/swoole/yasd/runs/5285563445?check_suite_focus=true

Ok now

**Pull request merged**
